apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  description: Questa task rimuove tutti i file dal workspace condiviso all'inizio della PipelineRun per garantire una directory di lavoro pulita.
  workspaces:
    - name: source
  steps:
    - name: remove
      # Immagine leggera contenente strumenti Unix di base (come rm)
      image: alpine:3 
      
      # Necessario per definire la variabile d'ambiente WORKSPACE_SOURCE_PATH che punta al volume montato
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
          
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        # Lo script deve essere robusto per rimuovere il contenuto del volume montato
        set -eu
        
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} except '..'"
        
        # Logica per rimuovere tutti i contenuti eccetto la directory padre (..)
        # Questo garantisce che il volume montato venga pulito senza smontare il volume stesso.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
            # Rimuove file e directory non nascoste
            rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
            # Rimuove file e directory nascoste (che iniziano con .) ma escludendo . e ..
            rm -rf "${WORKSPACE_SOURCE_PATH:?}"/.[!.]* "${WORKSPACE_SOURCE_PATH:?}"/..?*
        fi
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose
spec:
  description: Questa task esegue i test unitari Python utilizzando il modulo Nose.
  workspaces:
    - name: source
  params:
    - name: args
      description: Argomenti da passare a nosetests
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim # Immagine Python richiesta dal lab
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        
        # 1. Installazione di wheel e dipendenze
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        # 2. Installazione di nose (necessario per eseguire il comando)
        pip install nose
        
        # 3. Esecuzione dei test con gli argomenti forniti dal parametro
        nosetests $(params.args)